### ISSUE TITLE
Issues in Firefox and Safari when combined with core-menu-button

### ISSUE THREAD

**Issue by jakemac53** [Polymer/core-splitter#17]
If you have a core-splitter and a core-menu-button then after opening and closing the menu the splitter stops behaving properly.

Pure JS repro: http://jsbin.com/mexiwafuje/1/edit?html,output

Original report https://groups.google.com/a/dartlang.org/forum/?utm_medium=email&utm_source=footer#!msg/web/ahHE8RWi8yA/vM_NfmoiLGsJ

**Comment by frankiefu** [comment]
Seems like an issue in polymer-gestures.  When I close the popup menu, the events (mousedown, mousemove and mouseup) are also getting removed from the body.  Those events on the body are necessary for `track` to work properly.

**Comment by azakus** [comment]
Also broken in Chrome when ShadowDOM Polyfill is forced.

**Comment by azakus** [comment]
Found it. core-overlay adds and removes some capturing event handlers on document. The gesture recognizers treat event listener removals on document specially for mouse and PointerEvents for touch-like event handling.

Comparisons with the bare document reference fail in ShadowDOM.
